version: '3'

services:

  node_nginx:
    image: dhbart/nginx:1.21-alpine
    build:
      context: ./node_nginx
    container_name: node_nginx
    tty: true
    restart: always
    command: dockerize -wait tcp://app:3000 -timeout 20s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app
    

  app:
    image: dhbart/node:17-alpine
    container_name: app
    tty: true
    restart: always
    command: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh sh -c "npm install && node index.js --port 3000"
    build: 
      context: ./node
    ports:
      - "3000:3000"
    volumes:
      - "./node:/var/www/html"
    networks:
      - node-network
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network


networks: 
  node-network:     
    driver: bridge